remote: true
experienceLevel:
    internship: false
    entry: true
    associate: true
    mid-senior level: true
    director: false
    executive: false
jobTypes:
    full-time: true
    contract: true
    part-time: false
    temporary: false
    internship: false
    other: false
    volunteer: false
date:
    all time: false
    month: false
    week: true
    24 hours: false
positions:
- Python Developer
- Software Engineer
- Backend Engineer
- Automation Specialist
- Quantitative Developer
locations:
- London
- United Kingdom
- Remote
- European Economic Area
location_blacklist: []
distance: 100
company_blacklist:
- Crossover
- Wayfair
title_blacklist:
- Junior
- Intern
llm_model_type: gemini
llm_model: gemini-2.0-flash, gemini-flash-latest, gemini-pro-latest, gemini-2.0-flash-001
headless: false
apply_once_at_company: true
job_applicants_threshold:
    min_applicants: 0
    max_applicants: 100
learned_easy_apply_xpath: //a[contains(., 'Apply')]
learned_job_description_xpath: null
learned_scrollable_element_xpath: //main
learned_job_list_container_xpath: null
learned_primary_button_xpath: null
